Repository sneikki/tidgrid, pull requests merged in 2023-02, with the labels that each got.

#5 Update project description
  README.md
Labels: documentation

#23 Add rules for Stylelint & update Makefile
  .stylelintrc.json
  Makefile
Labels: meta

#32 Changes to .gitignore and Makefile
  .gitignore
  Makefile
Labels: meta

#52 Merge test and lint workflows
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: meta

#57 Initial website
  .gitignore
  site/404.html
  site/Gemfile
  site/Gemfile.lock
  site/_config.yml
  site/_includes/footer.html
  site/_includes/header.html
  site/_layouts/base.html
  site/about.markdown
  site/assets/favicons/android-chrome-192x192.png
  site/assets/favicons/android-chrome-512x512.png
  site/assets/favicons/apple-touch-icon.png
  site/assets/favicons/favicon-16x16.png
  site/assets/favicons/favicon-32x32.png
  site/assets/tidgrid-logo.svg
  site/index.md
Labels: documentation, meta

#61 Minor bug fixes and improvements
  src/grid/cell.scss
  src/grid/gap.scss
  src/grid/row.scss
  src/variant.scss
Labels: enhancement

#66 Remove top-layout layout modifiers
  src/layout/index.scss
Labels: enhancement
